# .cmake-format.yaml
format:
    line_width: 120
    dangle_parens: true
    use_tabchars: true
    tab_size: 4
    separate_fn_name_with_space: true
    max_subgroups_hwrap: 2
    dangle_align: "prefix-indent"
    keyword_case: "upper"
    always_wrap: true

markup:
    canonicalize_hashrulers: true
    enable_markup: true

encode:
    input_encoding: "utf-8"
    output_encoding: "utf-8"
    newline: "lf"
    ensure_newline_at_eof: true
    preserve_trailing_whitespace: false
