features:
    enable_full_psdk: true # 启用完整 PSDK 作业流程
    enable_status_board: true # 启用终端状态板
    enable_trace_log: true # 启用更详细日志
    set_psdk_log_level: 2 # 设置 PSDK 日志级别, 0=ERROR , 1=WARN , 2=INFO , 3=DEBUG
    skip_rc: false # 尝试跳过遥控器检测
    save_kmz_file: true # 保存 KMZ 文件到本地

catalog:
    node_id: CATF4KHZBF8
    port: 30906
    targets:
        - 192.168.1.131
        - 192.168.1.*

plane:
    code: 0A1B2C3D4E5F6078 # 飞机唯一16位识别码
    use_mqtt_v5_server: true # 使用 MQTT v5
    waypoint_3d_distance_tolerance: 0.5 # 3D 航点距离容差 (m)
    stick_sensitivity: 0.33 # 摇杆灵敏度 0.1~1.0
    tcp_frame_server_port: 1234 # TCP 帧服务端口
    service_reconnect_interval_s: 2 # 服务重连间隔 (s)
    max_waypoints_per_mission: 500 # 单任务最大航点数
    max_total_waypoints: 1000 # 最大总航点数
    gps_satellite_alert_threshold: 15 # GPS 卫星告警阈值
    video_quality_level: 75 # 视频质量等级 10~100
    simulator_default_longitude: "118.892591" # 模拟器默认经度
    simulator_default_latitude: "32.067228" # 模拟器默认纬度
    simulator_default_gps_count: "15" # 模拟器默认卫星数量
    custom_central_meridian: 0.0 # 自定义中央子午线 (度)
